package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {

     private String users;
     private String password;
     private int role;

    public Account() {
    }

    public Account(Account account, String users, String password) {

       this.users = users;
       this.password = password;
       this.role = role;
    }
    public String getUsers() {
        return this.users;
    }
    
    public void setUsers(String users) {
        this.users = users;
    }
    public String getPassword() {
        return this.password;
    } 
    public void setPassword(String password) {
        this.password = password;
    }
    public int getRole() {
        return this.role;
    } 
    public void setRole(int role) {
        this.role=role;
    }



}


