package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donban generated by hbm2java
 */
public class Donban  implements java.io.Serializable {


     private String maHdb;
     private Date ngayBan;
     private Set hoadonbans = new HashSet(0);

    public Donban() {
    }

	
    public Donban(String maHdb, Date ngayBan) {
        this.maHdb = maHdb;
        this.ngayBan = ngayBan;
    }
    public Donban(String maHdb, Date ngayBan, Set hoadonbans) {
       this.maHdb = maHdb;
       this.ngayBan = ngayBan;
       this.hoadonbans = hoadonbans;
    }
   
    public String getMaHdb() {
        return this.maHdb;
    }
    
    public void setMaHdb(String maHdb) {
        this.maHdb = maHdb;
    }
    public Date getNgayBan() {
        return this.ngayBan;
    }
    
    public void setNgayBan(Date ngayBan) {
        this.ngayBan = ngayBan;
    }
    public Set getHoadonbans() {
        return this.hoadonbans;
    }
    
    public void setHoadonbans(Set hoadonbans) {
        this.hoadonbans = hoadonbans;
    }




}


