package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donnhap generated by hbm2java
 */
public class Donnhap  implements java.io.Serializable {


     private String maHdn;
     private Date ngayNhap;
     private Set hoadonnhaps = new HashSet(0);

    public Donnhap() {
    }

	
    public Donnhap(String maHdn, Date ngayNhap) {
        this.maHdn = maHdn;
        this.ngayNhap = ngayNhap;
    }
    public Donnhap(String maHdn, Date ngayNhap, Set hoadonnhaps) {
       this.maHdn = maHdn;
       this.ngayNhap = ngayNhap;
       this.hoadonnhaps = hoadonnhaps;
    }
   
    public String getMaHdn() {
        return this.maHdn;
    }
    
    public void setMaHdn(String maHdn) {
        this.maHdn = maHdn;
    }
    public Date getNgayNhap() {
        return this.ngayNhap;
    }
    
    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }
    public Set getHoadonnhaps() {
        return this.hoadonnhaps;
    }
    
    public void setHoadonnhaps(Set hoadonnhaps) {
        this.hoadonnhaps = hoadonnhaps;
    }




}


