package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hanghoa generated by hbm2java
 */
public class Hanghoa  implements java.io.Serializable {


     private String maHh;
     private Nhacungcap nhacungcap;
     private String tenHh;
     private String mota;
     private int giaBan;
     private Set hoadonnhaps = new HashSet(0);

    public Hanghoa() {
    }

	
    public Hanghoa(String maHh, Nhacungcap nhacungcap, String tenHh, String mota, int giaBan) {
        this.maHh = maHh;
        this.nhacungcap = nhacungcap;
        this.tenHh = tenHh;
        this.mota = mota;
        this.giaBan = giaBan;
    }
    public Hanghoa(String maHh, Nhacungcap nhacungcap, String tenHh, String mota, int giaBan, Set hoadonnhaps) {
       this.maHh = maHh;
       this.nhacungcap = nhacungcap;
       this.tenHh = tenHh;
       this.mota = mota;
       this.giaBan = giaBan;
       this.hoadonnhaps = hoadonnhaps;
    }
   
    public String getMaHh() {
        return this.maHh;
    }
    
    public void setMaHh(String maHh) {
        this.maHh = maHh;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public String getTenHh() {
        return this.tenHh;
    }
    
    public void setTenHh(String tenHh) {
        this.tenHh = tenHh;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public int getGiaBan() {
        return this.giaBan;
    }
    
    public void setGiaBan(int giaBan) {
        this.giaBan = giaBan;
    }
    public Set getHoadonnhaps() {
        return this.hoadonnhaps;
    }
    
    public void setHoadonnhaps(Set hoadonnhaps) {
        this.hoadonnhaps = hoadonnhaps;
    }




}


