package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hoadonnhap generated by hbm2java
 */
public class Hoadonnhap  implements java.io.Serializable {


     private Date ngayNhap;
     private Donnhap donnhap;
     private Hanghoa hanghoa;
     private Nhacungcap nhacungcap;
     private Nhanvien nhanvien;
     private String tenHh;
     private String mota;
     private int donGia;
     private int soLuong;
     private String dvt;
     private int tongTien;
     private String tenNv;

    public Hoadonnhap() {
    }

    public Hoadonnhap(Date ngayNhap, Donnhap donnhap, Hanghoa hanghoa, Nhacungcap nhacungcap, Nhanvien nhanvien, String tenHh, String mota, int donGia, int soLuong, String dvt, int tongTien, String tenNv) {
       this.ngayNhap = ngayNhap;
       this.donnhap = donnhap;
       this.hanghoa = hanghoa;
       this.nhacungcap = nhacungcap;
       this.nhanvien = nhanvien;
       this.tenHh = tenHh;
       this.mota = mota;
       this.donGia = donGia;
       this.soLuong = soLuong;
       this.dvt = dvt;
       this.tongTien = tongTien;
       this.tenNv = tenNv;
    }
   
    public Date getNgayNhap() {
        return this.ngayNhap;
    }
    
    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }
    public Donnhap getDonnhap() {
        return this.donnhap;
    }
    
    public void setDonnhap(Donnhap donnhap) {
        this.donnhap = donnhap;
    }
    public Hanghoa getHanghoa() {
        return this.hanghoa;
    }
    
    public void setHanghoa(Hanghoa hanghoa) {
        this.hanghoa = hanghoa;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getTenHh() {
        return this.tenHh;
    }
    
    public void setTenHh(String tenHh) {
        this.tenHh = tenHh;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public int getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(int donGia) {
        this.donGia = donGia;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public String getDvt() {
        return this.dvt;
    }
    
    public void setDvt(String dvt) {
        this.dvt = dvt;
    }
    public int getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(int tongTien) {
        this.tongTien = tongTien;
    }
    public String getTenNv() {
        return this.tenNv;
    }
    
    public void setTenNv(String tenNv) {
        this.tenNv = tenNv;
    }




}


