package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private String maKh;
     private String tenKh;
     private String cmnd;
     private int soDt;
     private String diaChi;
     private Integer tichDiem;
     private Set hoadonbans = new HashSet(0);

    public Khachhang() {
    }

	
    public Khachhang(String maKh, String tenKh, String cmnd, int soDt, String diaChi) {
        this.maKh = maKh;
        this.tenKh = tenKh;
        this.cmnd = cmnd;
        this.soDt = soDt;
        this.diaChi = diaChi;
    }
    public Khachhang(String maKh, String tenKh, String cmnd, int soDt, String diaChi, Integer tichDiem, Set hoadonbans) {
       this.maKh = maKh;
       this.tenKh = tenKh;
       this.cmnd = cmnd;
       this.soDt = soDt;
       this.diaChi = diaChi;
       this.tichDiem = tichDiem;
       this.hoadonbans = hoadonbans;
    }
   
    public String getMaKh() {
        return this.maKh;
    }
    
    public void setMaKh(String maKh) {
        this.maKh = maKh;
    }
    public String getTenKh() {
        return this.tenKh;
    }
    
    public void setTenKh(String tenKh) {
        this.tenKh = tenKh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public int getSoDt() {
        return this.soDt;
    }
    
    public void setSoDt(int soDt) {
        this.soDt = soDt;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Integer getTichDiem() {
        return this.tichDiem;
    }
    
    public void setTichDiem(Integer tichDiem) {
        this.tichDiem = tichDiem;
    }
    public Set getHoadonbans() {
        return this.hoadonbans;
    }
    
    public void setHoadonbans(Set hoadonbans) {
        this.hoadonbans = hoadonbans;
    }




}


