package Enities;
// Generated 14-May-2020 18:06:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap  implements java.io.Serializable {


     private String maNhaCc;
     private String tenNhaCc;
     private Set hoadonnhaps = new HashSet(0);
     private Set hanghoas = new HashSet(0);

    public Nhacungcap() {
    }

	
    public Nhacungcap(String maNhaCc, String tenNhaCc) {
        this.maNhaCc = maNhaCc;
        this.tenNhaCc = tenNhaCc;
    }
    public Nhacungcap(String maNhaCc, String tenNhaCc, Set hoadonnhaps, Set hanghoas) {
       this.maNhaCc = maNhaCc;
       this.tenNhaCc = tenNhaCc;
       this.hoadonnhaps = hoadonnhaps;
       this.hanghoas = hanghoas;
    }
   
    public String getMaNhaCc() {
        return this.maNhaCc;
    }
    
    public void setMaNhaCc(String maNhaCc) {
        this.maNhaCc = maNhaCc;
    }
    public String getTenNhaCc() {
        return this.tenNhaCc;
    }
    
    public void setTenNhaCc(String tenNhaCc) {
        this.tenNhaCc = tenNhaCc;
    }
    public Set getHoadonnhaps() {
        return this.hoadonnhaps;
    }
    
    public void setHoadonnhaps(Set hoadonnhaps) {
        this.hoadonnhaps = hoadonnhaps;
    }
    public Set getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set hanghoas) {
        this.hanghoas = hanghoas;
    }




}


